### ISSUE TITLE
MINIDAPP NAME - TEAM NAME

### ISSUE THREAD

**Issue by ErkanDERELI** [minima-global/innovation-challenge#10]
**Before you start, please update the issue title:**

Example: *Minima DEX - The A Team*

## :pencil2: Project & Team Details

1. MiniDapp/Project Name [required, as used in your Google Form]: *Provide the name of your MiniDapp/Project*

2. MiniDapp/Project Description [optional, if changed from your application in Google Form]: *Please provide a brief description of your MiniDapp/Project*

3. Team Name [optional, if changed from your application in Google Form]: *Provide your team name*

4. Team Members [optional, if changed from your application in Google Form]: *Please list names of all team members*

## :one: Phase 1 Submission 

For Phase 1, please upload the following 
(paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)

5. A whitepaper or a pitch video with a description of the idea you have that includes: your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution.

6. Upload Presentation: *Upload any relevant presentations/slide decks you have created*

## :two: Phase 2 Submission 

For Phase 2, please update your submission, providing the following:

7. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

8. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

9. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [ ] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [ ] You have followed the issue title format
- [ ] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [ ] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by martapiekarska** [comment]
Hi, this submission is empty. **Can you please upload the documents**

**Comment by ErkanDERELI** [comment]
> **Before you start, please update the issue title:**
> 
> Example: _Minima DEX - The A Team_
> 
> ##  Project & Team Details
> 1. MiniDapp/Project Name [required, as used in your Google Form]: _Provide the name of your MiniDapp/Project_
> 2. MiniDapp/Project Description [optional, if changed from your application in Google Form]: _Please provide a brief description of your MiniDapp/Project_
> 3. Team Name [optional, if changed from your application in Google Form]: _Provide your team name_
> 4. Team Members [optional, if changed from your application in Google Form]: _Please list names of all team members_
> 
> ##  Phase 1 Submission
> For Phase 1, please upload the following (paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)
> 
> 5. A whitepaper or a pitch video with a description of the idea you have that includes: your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution.
> 6. Upload Presentation: _Upload any relevant presentations/slide decks you have created_
> 
> ##  Phase 2 Submission
> For Phase 2, please update your submission, providing the following:
> 
> 7. Code Repository Link: _Provide a link to the Github URL (or other) for your MiniDapp/Project_
> 8. Upload MiniDapp: _If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension_
> 9. Upload Demo: _Upload any demonstration videos you have created (optional)_
> 
> ##  Other Comments
> _Optional - add any other comments regarding your submission_
> 
> ##  Checklist
> **Before you post the issue**:
> 
> * [ ]  Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
> * [ ]  You have followed the issue title format
> * [ ]  You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
> * [ ]  You have read and agree with the terms in the Code Of Conduct
