### ISSUE TITLE
MINIDAPP Nixie - TEAM Reedyx

### ISSUE THREAD

**Issue by Franknoir** [minima-global/innovation-challenge#13]
**Before you start, please update the issue title:**

Example: *Minima DEX - The A Team*

## :pencil2: Project & Team Details

1. MiniDapp/Project Name -Nixie

2. MiniDapp/Project Description -Do you remember the hype that was with Pokemon go? 
The idea of the project is to do something similar, but it will be a web3 application.
In our game you will be able to catch "critters" that are real Nft on the Minima blockchain. You'll be able to upgrade them, fight them, brind them for further trading on the marketplace, and learn LOR. You will be able to join guilds with other players and participate in tournaments.

3. Team Name -Reedyx

4. Team Members -Now our team consists of three people: Vlad, Veronica, Dmitriy

## :one: Phase 1 Submission 

For Phase 1, please upload the following 
(paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)

5. A whitepaper or a pitch video with a description of the idea you have that includes: your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution.
VIDEO-https://drive.google.com/file/d/1f_SbN6F8ZsCe7qyv8TFDoZus0s4jnets/view?usp=sharing

7. Upload Presentation: 
[Reedyx (3).pdf](https://github.com/minima-global/innovation-challenge/files/9266041/Reedyx.3.pdf)

## :two: Phase 2 Submission 

For Phase 2, please update your submission, providing the following:

8. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

9. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

10. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [x] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [x] You have followed the issue title format
- [x] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [x] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
