### ISSUE TITLE
Trust Market - Trust Team

### ISSUE THREAD

**Issue by lMadaraUchihal** [minima-global/innovation-challenge#16]
**Before you start, please update the issue title:**

Example: *Minima DEX - The A Team*

## :pencil2: Project & Team Details

1. MiniDapp/Project Name: Trust Market

2. MiniDapp/Project Description: My dream is a safe internet zone.  The idea of ​​the project is to create a safe OTC platform where scam will be impossible. At the moment, the process of buying accounts, whitelist, etc. is very laborious, expensive and 99% unreliable without escrow.  We propose to create a platform where there will be a fixed commission for a transaction, will be created a NFT collection for sellers, which will reduce the commission fee for the buyer and make the offer of this seller more interesting.
 Someone found out about the project late and wants to get its product?
 Trust Market will allow you to do it quickly, cheaply and safely!

3. Team Name: Trust Team

4. Team Members: No members

## :one: Phase 1 Submission 

For Phase 1, please upload the following 
(paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)

5. A whitepaper or a pitch video with a description of the idea you have that includes: your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution. [Trust Market with voice.pptx](https://github.com/minima-global/innovation-challenge/files/9271270/Trust.Market.with.voice.pptx) - Presentation with a voice-over 

6. Upload Presentation: *Upload any relevant presentations/slide decks you have created*
[Trust Market.pptx](https://github.com/minima-global/innovation-challenge/files/9271264/Trust.Market.pptx) - Classic presentation

## :two: Phase 2 Submission 
[Trust Market with voice.pptx](https://github.com/minima-global/innovation-challenge/files/9271270/Trust.Market.with.voice.pptx)

For Phase 2, please update your submission, providing the following:

7. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

8. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

9. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [x] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [x] You have followed the issue title format
- [x] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [x] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
