### ISSUE TITLE
Unblock the food chain ep II

### ISSUE THREAD

**Issue by Hommedeterre** [minima-global/innovation-challenge#18]
I want to use Minima to transfer food data up the chain to help buyers select the right food and see the social value of their choices mount up.

**Comment by martapiekarska** [comment]
Hi please submit the full pitch deck and a short video/whitepaper describing your idea

**Comment by Hommedeterre** [comment]
Hi, I’m about to get on and finish & send. I’ll be in touch if GitHub doesn’t let me see part I application. Sorry I’m late, I should be 2-3 hours I hope. 
Best wishes
AJ

**Comment by Hommedeterre** [comment]
✏️ Project & Team Details

MiniDapp/Project Name: Provide the name of your MiniDapp/Project
**Unblock the food chain ep II**

MiniDapp/Project Description: Please provide a brief description of your MiniDapp/Project
**I want to use Minima to transfer food data up the chain to help buyers select the right food and see the social value of their choices mount up.**
Team Name: Provide your team name
**Hommedeterre**
Team Members: Please list names of all team members
**Andy Johnson**
1️⃣ Phase 1 Submission

For Phase 1, please provide the following:

A recording of a 3-5 minute pitch presentation: Please explain your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution

![4ECFDEB0-58C1-4591-9C76-D15CD7DF6EA7_1_105_c](https://user-images.githubusercontent.com/110697701/183437135-e7cae569-892a-40e7-a97c-e4a609a7d793.jpeg)

Upload Presentation: Upload any relevant presentations/slide decks you have created
**Metric, GFM & reduced data for this trial**
![Metrics](https://user-images.githubusercontent.com/110697701/183445085-3860209c-b7e7-4b12-bda8-98fad59b582e.png)
[farm token.pdf](https://github.com/minima-global/innovation-challenge/files/9282662/farm.token.pdf)
**Data flows to Citizens & money back to the producers**
![Data   Money flow](https://user-images.githubusercontent.com/110697701/183445174-8265ff6b-8d49-4382-8c52-e3802bb14be9.png)
**Project outline**
[Unblocking the food chain outline.docx](https://github.com/minima-global/innovation-challenge/files/9283156/Unblocking.the.food.chain.outline.docx)


2️⃣ Phase 2 Submission

For Phase 2, please update your submission, providing the following:

Code Repository Link: Provide a link to the Github URL (or other) for your MiniDapp/Project
**n/a**
Upload MiniDapp: If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the .mds.zip extension
**n/a**
Upload Demo: Upload any demonstration videos you have created (optional)

📍 Other Comments

Optional - add any other comments regarding your submission

✔️ Checklist

Before you post the issue:

  Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
  You have followed the issue title format
  You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
  You have read and agree with the terms in the [Code Of Conduct](https://github.com/minima-global/innovation-challenge/issues/18)

**Comment by Hommedeterre** [comment]
Entry completed at 16.48 BST. Sorry so late, thank you for your patience.
AJ

**Comment by Hommedeterre** [comment]
Hello, I'm through to the next part of the challenge, possibly the most challenging so far...

I need some help with getting the next part started - aligning my data with minima and testing the links before moving to the next stage, simulating the addition of data as food moved down the chain to give a cumulative set of data at the point of final sale.

my email is hommedeterre@icloud.com, tel 07980 746622

Thanks, aj

**Comment by martapiekarska** [comment]
Hi Team! Can I please ask you to confirm that you are working on your final submission - the final deadline is 12th of September. Please try taking the continuous submission approach rather than send everything at once. This will help judges and show the journey you’re taking and the thought process.

**Comment by Hommedeterre** [comment]
The Challenge was tough, the coding stage is still to be done and partners who can help need finding. Apart from that, it's finished!

[Lets-unblock the foodchain.docx](https://github.com/minima-global/innovation-challenge/files/9579381/Lets-unblock.the.foodchain.docx)

**Comment by Hommedeterre** [comment]
I can do no more, see you in London.

Best wishes

AJ
