### ISSUE TITLE
Kairos - Kairos Blockchain for students

### ISSUE THREAD

**Issue by kairos000** [minima-global/innovation-challenge#19]
1. MiniDapp/Project Name: Kairos

2. MiniDapp/Project Description: Kairos is a website that provides a completely free education platform for students to learn about the different aspects of the ecosystem. Each partner company provides a complete education from three angles: the programming language of their company, a presentation of the company and how it works, and a training on the company's marketing & entrepreneurship model. Students who have completed a course are given the opportunity to take advantage of an incubator that provides them with help from our partners to develop the best innovative projects among young people.

3. Team Name: Kairos Team

4. Team Members: 
LDM:
-In the crypto ecosystem for 4 years
-Wealth management student at Paris-Dauphine
-Founder of two former trading companies, one of them specialized in cryptocurrencies
-Currently working as Head of Token Growth for Arianee Protocol
-Working with Web3 projects to improve their tokenomics

Lwi
-Started crypto in 2020
-Founder and president of Kryptosphere Dau, a student blockchain society at Université Paris-Dauphine PSL
-Student in economics and management at Université Paris- Dauphine PSL

[Our goal .pdf](https://github.com/minima-global/innovation-challenge/files/9273247/Our.goal.pdf)
pitch to download : https://we.tl/t-OpeTnN74Cn

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
