### ISSUE TITLE
sf-library - sff-stake

### ISSUE THREAD

**Issue by Semenyuk62** [minima-global/innovation-challenge#21]
sf-library - sff-stake

[sf-library.zip](https://github.com/minima-global/innovation-challenge/files/9275494/sf-library.zip)

Our idea in development. 
Our idea is - decentralized nano library with real-time information loading. With the possibility of buying books using MiniDapp.
minima is the simplest and fastest solution. I have been with Minima since the first days and my desire to create is thanks to Minima. payment using a minima token, decentralization, speed, loading information from the blockchain

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
