### ISSUE TITLE
İnstant Diagnosis - TestTR

### ISSUE THREAD

**Issue by ErkanDERELI** [minima-global/innovation-challenge#24]
**Project & Team  Details**

**MiniDapp/Project Name**: Writing Vehicles and Driver Data to Blockchain.

**MiniDapp/Project Description** : Which of us do not use Internet History Records? Doesn't it Provide Convenience? As vehicle manufacturer (or Authorized Service) or Driver (only driver actions); Wouldn't it be nice to keep records of all the data of our vehicle? I think it will be useful in many ways. In particular, the fact that this data is always accessible and unchangeable will be a reliable source of information about that vehicle.Abnormal sensor data (may be early diagnosis) to the vehicle manufacturer (service) transmission, transferring data to the manufacturer in speed-limited vehicles, illegal interventions. Or in electric vehicles; Use it as a means of payment at charging stations. Like this... In short, the vehicle network era should start with minima. Today, ECU data is accessed via can-bus protocol in existing vehicles. These data can be streamed onto the minima network.

**Team Name:** TestTR

**Team Members :**  Erkan DERELİ

[Writing vehicles and driver data to.pptx](https://github.com/minima-global/innovation-challenge/files/9277321/Writing.vehicles.and.driver.data.to.pptx)

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
