### ISSUE TITLE
MINIDAPP DIGIEX - TEAM LUMIAR

### ISSUE THREAD

**Issue by mityamamont** [minima-global/innovation-challenge#6]
**Before you start, please update the issue title:**

Example: *Minima DEX - The A Team*

## :pencil2: Project & Team Details

1. MiniDapp/Project Name - Digiex

2. MiniDapp/Project Description - Online stores: stuff, clothes, food, branding services.  Or production of anything.
For example, everyone can create their own merchandise store on the basis of daps. Created a brand, shows his brand with trustworthy videos. Created a token, and nft as a product. And for the tokens will buy those nft.  This could solve the problem of fakes in the future, or if you buy a fake, you'll know about it before you buy it... Whereas now many sellers sell a copy under the guise of the original... and the customer thinks he is buying the original. 
Minima is the replacement for Amazone or Ebay here.

3. Team Name - Lumiar

4. Team Members - At the moment the team consists of 3 people: Dmitry, Artem, Nicholas.

## :one: Phase 1 Submission 

For Phase 1, please upload the following 
(paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)

5. A whitepaper or a pitch video with a description of the idea you have that includes: your idea, how it meets the criteria to be considered for the competition, the benefits it will bring to people and how the unique features of the Minima network can make a real difference/give an advantage to your solution.

https://user-images.githubusercontent.com/101664221/182799679-eade9cf4-abe7-47f7-ad09-50029619a299.mp4

6. Upload Presentation: *Upload any relevant presentations/slide decks you have created* 
[Lumiar.pdf](https://github.com/minima-global/innovation-challenge/files/9257943/Lumiar.pdf)

## :two: Phase 2 Submission 

For Phase 2, please update your submission, providing the following:

8. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

9. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

10. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [x] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [x] You have followed the issue title format
- [x] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [x] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
