### ISSUE TITLE
MINIDAPP MASS Media - TEAM Lumiar 

### ISSUE THREAD

**Issue by XPERT1000** [minima-global/innovation-challenge#7]
1. MiniDapp/Project Name [ MASS media 

2. MiniDapp/Project Description . Media
Problems in today media
We found several majors problems, 
Such is censorship and distortion of broadcast information, because it remains a centralized and just outdated web2 system. 
Media will be decentralized 
No one can influence the media, not even politicans can shut down a channel or keep silent about what needs to be talked about 
Decentralized media Info =NFT. 
If the media gives distorted news, false information, the audience whil choose another competing media outlet. Media channels will compete with  each other for quality content. 
The sum insured must be 10 % than the total amount from the subscribers who bought  the information in the form of nft. 
Example 
1000 people =1000 nft= 1100token mass media. 
Agents will be able  to earn money  by identifying inaccurate information. 
. 

3 Team Name Lumiar. 

4. Team Members [#Xpert0766- (Artem) nik911#2629(Nikolay) mamont#2848 (Dmitry  ()

5) video presentation
https://fex.net/uk/s/eycsnxy

6.  Presentation Image: 
 https://fex.net/uk/s/yp852ro

## :two: Phase 2 Submission 

For Phase 2, please update your submission, providing the following:

9. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

10. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

11. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [ ] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [ ] You have followed the issue title format
- [ ] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [ ] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by Nikolapak** [comment]
отлично, какие планы?

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
