### ISSUE TITLE
MINIDAPP GemPost - TEAM Lumiar

### ISSUE THREAD

**Issue by Nikolapak** [minima-global/innovation-challenge#9]
**Before you start, please update the issue title:**

Example: *Minima DEX - Team Lumiar

## :pencil2: Project & Team Details

1. MiniDapp/Project Name GemPost

2. MiniDapp/Project Description GemPost is a new approach for solving the delivery of goods to the consumer. 
There are several problems for logistics companies that cannot be solved by the traditional method of delivery 

 1 Goods are not delivered to many countries for various reasons 
 2. In some countries delivery is very expensive can exceed the product itself several times.
 3. Long waiting time, sometimes up to several months.
 4. Parcel is not tracked all the way through.
 5. 5. Parcel is lost during the long journey.
 6. Parcels are not delivered on weekends and holidays. 
Today people use internet-shop more and more. And very often they order goods from abroad with the help of this application built on the blockchain Minima. It will be possible to solve it completely. Now the parcel transfer will be so fast and so cheap ... that will increase the sales of online stores several times over. People will not have to wait months for parcels and overpay for speed ... they will get their goods at an affordable, safe, and sound price. 
 GemPost on the blockchain Minima will completely solve this problem with the app  
 Why Minima? Because it's already integrated into our smartphones. And we only need to connect with this application that will unite the Minima community even more. And will become one of the most popular blockchains. 

3. Team Name Lumiar

4. Team Members Nikolay, Artem, Dmitry

## :one: Phase 1 Submission 

For Phase 1, please upload the following 
(paste the link to where you uploaded e.g. other cloud provider or GitHub (if more than 100MB) or Attach files by dragging & dropping, selecting or pasting them)

5 https://drive.google.com/file/d/142HduQ5xTSuuYZZF0Lau8FYltfD3-Acf/view?usp=sharing 

6. Upload Presentation: 
[GemPost Minina presentation.pdf](https://github.com/minima-global/innovation-challenge/files/9260879/GemPost.Minina.presentation.pdf)

## :two: Phase 2 Submission 

For Phase 2, please update your submission, providing the following:

7. Code Repository Link: *Provide a link to the Github URL (or other) for your MiniDapp/Project*

8. Upload MiniDapp: *If your project includes a MiniDapp, please upload your MiniDapp - this should be a .zip file using the **.mds.zip** extension*

9. Upload Demo: *Upload any demonstration videos you have created (optional)*

##  :round_pushpin: Other Comments
*Optional - add any other comments regarding your submission*

## :heavy_check_mark: Checklist

**Before you post the issue**:
- [ ] Make sure you have entered using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdW-r1iTN2JUxaLhKZxLj4FgRnIF6yZWAXB30hj4c-vwaNuPw/viewform)
- [ ] You have followed the issue title format
- [ ] You have provided all the information correctly and uploaded all required material for the Phase you are submitting for
- [ ] You have read and agree with the terms in the [Code Of Conduct]()

**Comment by Jazminima** [comment]
As this entry was not a chosen finalist of this competition, we will now close the issue. 
We would like to thank you for your submission and would encourage you to continue development of the idea. Alternative competitions may take place in the future.

The Minima and Edenbase Team
